dist: xenial

sudo: required

language: rust

rust:
  - nightly-2019-06-20

cache: cargo

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin --force
  fi

before_install:
  - set -e
  - rustup self update

install:
  - echo "installing clippy"
  - rustup component add clippy
  - echo "clippy installed"

script:
  - cargo clean --all
  - cargo build --all --verbose
  - cargo clippy --all --verbose
  - cargo test --all --verbose

after_script:
  - set +e

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly-2019-06-20 ]]; then
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi

notifications:
  email:
    on_success: never
