[package]
name = "store"
version = "0.1.0"
authors = ["chritchens <chritchens@gmail.com>"]
edition = "2018"

[dependencies]
failure = "~0.1"
serde = { version = "~1.0", features = ["derive"] }
serde_cbor = "~0.10"
tempfile = "~3.1"
unqlite = "~1.4"

crypto = { path = "../crypto" }
