[package]
name = "cli"
version = "0.1.0"
authors = ["chritchens <chritchens@gmail.com>"]
edition = "2018"

[dependencies]
failure = "~0.1"
enum-display-derive = "~0.1"
serde = { version = "~1.0", features = ["derive"] }
serde_cbor = "~0.10"
serde_json = "~1.0"
chrono = "~0.4"
num = { version = "~0.2", features = ["std", "rand", "serde"] }
futures-preview = { version = "=0.3.0-alpha.17", features = ["async-await", "nightly"] }
may = "~0.3"
generator = "~0.6"
conetty = { git = "https://github.com/Xudong-Huang/conetty" }
may_signal = { git = "https://github.com/Xudong-Huang/may_signal" }
may_process = { git = "https://github.com/Xudong-Huang/may_process" }
may_thread = { git = "https://github.com/Xudong-Huang/may_thread" }
may_rpc = { git = "https://github.com/Xudong-Huang/may_rpc" }
clap = { version = "~2", features = ["suggestions", "color", "vec_map", "yaml", "wrap_help"] }

crypto = { path = "../crypto" }
mining = { path = "../mining" }
store = { path = "../store" }
models = { path = "../models" }
network = { path = "../network" }
consensus = { path = "../consensus" }
config = { path = "../config" }
